# Generated by Django 2.2.4 on 2019-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
