# Generated by Django 2.2.4 on 2019-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='text',
            field=models.TextField(default='', verbose_name='Текст модели'),
        ),
    ]
